### ISSUE TITLE
Different versions of @next/font

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/kaching-app#13]
Please address this warning during startup of the app

`warn  - Different versions of @next/font (13.2.0) and next (13.0.3) detected. This may lead to unexpected behavior.`

**Comment by alekseevaiana** [comment]
I can downgrade `@next/font` to 13.0.3 or I can upgrade `next`. 
> Starting with Next.js 13.2, next/font is built-in to Next.js and no longer needs to be installed. The @next/font package will be removed in Next.js 14.

https://nextjs.org/docs/messages/built-in-next-font
