### ISSUE TITLE
Page transitions

### ISSUE THREAD

**Issue by alekseevaiana** [UseKeyp/kaching-app#15]
There is a form on a send page, where you go from screen to screen filling out the form. We have to decide:
- how exactly transitions will look like. After a meeting with Sasha, we thought about 'to left' or 'to right' animated transition
- what happens when user clicks "back" button in the browser when user on `screen 2`
- for technical side we will use `react-step-wizard` https://www.npmjs.com/package/react-step-wizard

**Comment by pi0neerpat** [comment]
Please always add the label for the current chapter, and the project when creating an issue 
![image](https://github.com/UseKeyp/kaching-app/assets/35622595/9dcb933a-bb61-41cb-b718-3d8435c7311e)

**Comment by pi0neerpat** [comment]
Closing this as I think what you chose is fine for now
