### ISSUE TITLE
Kaching backgrounds

### ISSUE THREAD

**Issue by alekseevaiana** [UseKeyp/kaching-app#16]
On a new design we have colorful backgrounds, but we have to decide how to implement it from tech perspective. We might need to create new issues for that. Discuss it all together with Patrick, Jacob, Iana, and Sasha.
Figma file for reference: https://www.figma.com/file/cAvSKcYAOcVjK7RZeCWjlx/Kaching?type=design&node-id=812-2118&t=3NmSpt21SgAtMlSh-0

- on Figma file, backgrounds have multiple layers, and it could be complicated to code it, but we can use simple picture (png) for it. But images still doesn't look like on the Figma design.
- every screen has different background, and not clear how to implement it. My idea is using variables for body tag that depends on the page route, but not sure if we can use it with Chakra UI.

**Comment by pi0neerpat** [comment]
For this sprint, I think the only requirements is that the background is somewhat similar to the design- no need to match.

And that it changes when the page changes.
