### ISSUE TITLE
Kaching Redesign [6.5]: Asset selection

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/kaching-app#17]
Clicking in the box on the right screen should open the Asset Selection screen 

![image](https://github.com/UseKeyp/kaching-app/assets/35622595/20e58b2a-ed2f-481a-a7d5-3c99288867be)

**Comment by alekseevaiana** [comment]
Sasha changed design a little, so now we have a button to choose asset

![Image](https://github.com/UseKeyp/kaching-app/assets/36742189/775b8280-3a15-46d5-a8d0-d37f16fef586)
