### ISSUE TITLE
Create the basic scaffold of the new Kaching app

### ISSUE THREAD

**Issue by jahabeebs** [UseKeyp/kaching-app#2]
Step 2 of this issue: https://github.com/UseKeyp/kaching-app/issues/1

**Comment by alekseevaiana** [comment]
I started the issue right away, but didn't write a plan first. I've created a new PR #4 so you can take a look at code I implemented and wrote a plan below where I've detailed what I've already done and what remains to be completed.
> 2a. We should add the bluish background
- Have to check with Sasha what did we decide for background implementation and try what he suggested in a codepen example.

> 2b. refactor our user info into a new component that has the icon for the login provider (gmail for example), username, abbreviated wallet address, and profile picture: 
- Created new component UserAccount, but have to specify shadow color depending on a route
- I have to make it fixed on a page
- I did logout on a profile icon for testing login/logout, will remove it

> 2c. We need a new navbar component in the app + new buttons that will navigate us to different routes. The routes should be /wallet, /send, /ramp, /apps. Notice that the user info component should remain fixed at the top for each route. however, the backgrounds will change. don't worry about styling each of the pages for now--we just want to be able to navigate to different routes and have the user info component remained centered on each route:
- Updated Navbar
- Created new routes /wallet, /send, /ramp, /apps
- Added new icons components

## Questions
- Right now I put Navbar and UserAccount in an _app file, but not sure that it is a right solution. As I understand, right after login, user navigates to /wallet page. So I changed reidirect in login.tsx file. Is it right or we change the logic at the end?

**Comment by alekseevaiana** [comment]
Also, I played around with backgrounds, but I think we are going to change it to picture after all
