### ISSUE TITLE
Kaching Redesign [3]:  Create a tokens component 

### ISSUE THREAD

**Issue by jahabeebs** [UseKeyp/kaching-app#6]
Create a tokens component that will list the MATIC, USDC, and ETHEREUM that the logged in user has. In the future we can expand to more assets. 

- Each row will have an icon + name of the coin + balance of the coin + its price in dollars (save this step for last -- it will require some research on APIs to get the dollar value of a user's assets. talk to jacob when ready for this step). Note that Figma has icons for USDC, ETHEREUM, and MATIC.

In Kaching you can see we already have a bunch of assets for a particular user (photo below). Note that we won't do DAI for now and we need to add in ETHEREUM.

<img width="630" alt="Screenshot 2023-05-19 at 2 37 37 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/2a41f08c-a53f-44e7-bb5e-8830fcc4da6b">

For your information, here is a sample response from the API: 

```
{
    "MATIC": {
        "balance": "25000000000000000",
        "balanceBn": {
            "type": "BigNumber",
            "hex": "0x58d15e17628000"
        },
        "formatted": "0.025",
        "decimals": 18,
        "symbol": "MATIC",
        "name": "MATIC",
        "tokenAddress": null,
        "network": "POLYGON",
        "chainId": 137
    },
    "USDC": {
        "balance": "0",
        "balanceBn": {
            "type": "BigNumber",
            "hex": "0x00"
        },
        "formatted": "0.0",
        "decimals": "6",
        "symbol": "USDC",
        "name": "USD Coin (PoS)",
        "tokenAddress": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        "network": "POLYGON",
        "chainId": 137
    }
}
```

You may notice there are some very big numbers in the response. This is because they're BigNumber responses. Make sure to use the formatted value instead of the raw balance value for the component. Again, you shouldn't have to worry about this too much because Kaching is already currently using the formatted values but it's something to keep in mind.

- When pressing the fund or cash out button it should route the user to the /send page that we created in step 2.

final result:

<img width="308" alt="Screenshot 2023-05-19 at 2 21 47 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/eda77ad0-5640-483d-8393-2b6f74df9c33">

**Comment by alekseevaiana** [comment]
## Plan
Change design for Wallet.tsx component:
- render this component in /wallet page
- make a new style (frame, rows, icons, names)
- make redirect from Fund and Cash Out buttons to /send page
- make logic for showing price in dollar value for each token

PS: I think it can take more than 4 hours for me, but it depends on the last step.
