### ISSUE TITLE
Kaching Redesign [4]: Refactor the send page 

### ISSUE THREAD

**Issue by jahabeebs** [UseKeyp/kaching-app#7]
Refactor the send page to make it look like the designs. Don't worry about filling in a recipient or amount for now. You'll see that when we try to fill in a recipient or an amount in USDC it'll bring us to some new components which we'll complete in future steps.

send page

<img width="415" alt="Screenshot 2023-05-19 at 2 50 26 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/08400e05-c5f3-4b17-9365-a14e58bce301">

Currently in Kaching our send page looks like this: 

<img width="436" alt="Screenshot 2023-05-19 at 2 52 31 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/71220ac7-833e-4c32-bcc2-57801aca694e">

We need to do some refactoring to get the page looking like the design. Also note that we have an available balance amount which will be only the user's USDC balance because this is what we'll be supporting initially to send

<img width="222" alt="Screenshot 2023-05-19 at 3 06 52 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/56cad7bf-dd3c-46f5-bf4b-eca10e139646">

Acceptance criteria: 
- greenish background
- arrow icons
- 2 text input boxes you can type into with correct placeholder text
- send payment button that activates when info is filled in/deactivated when not filled in
- available USDC balance under text box

**Comment by alekseevaiana** [comment]
# Plan
- talk to Sasha about backgrounds and decide what is better way to do it
- add arrow icons
- add two text inputs with placeholders, but no need to filling in a recipient or amount for now.
- add 'send payment'  buttons with disabled state
- get available USDC balance from API and show it

**Comment by pi0neerpat** [comment]
Sounds good
