### ISSUE TITLE
QA Part 2

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/kaching-app#70]
# Account page
- Breaks when no transactions are present @alekseevaiana 

# Tokens page
- Should have a loading state @alekseevaiana. Loading state should show all the assets, but the values should be loading 
- If the api errors, should show the error message @alekseevaiana

**Comment by alekseevaiana** [comment]
@pi0neerpat I already have 34 transactions, maybe we have to limit our transaction number on page?  Could I limit by 10?

**Comment by pi0neerpat** [comment]
I think thats a good idea
