### ISSUE TITLE
Kaching Redesign [5]: Recipient toggle, confirm recipient

### ISSUE THREAD

**Issue by jahabeebs** [UseKeyp/kaching-app#8]
For now we should be able to toggle between Discord and Gmail. Note that the placeholder text should change when clicking between Gmail and Discord. The Twitter and Twitch icons can remain greyed out. 

- Create the confirm recipient button. After entering a username/email and pressing confirm recipient, it should bring the user back to the main page of /send and have their info auto-populated in the recipient field. Note that under the recipient field it says "sending to" and then the icon of the selected provider

after clicking the text input box for recipient (it will be blank originally)

<img width="298" alt="Screenshot 2023-05-19 at 3 10 52 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/8003240d-42cf-4ba0-85a7-df78f59ea4d5">

we get brought to this where we can select a provider/enter a recipient (see figma: https://www.figma.com/proto/cAvSKcYAOcVjK7RZeCWjlx/Kaching?node-id=902-5460&starting-point-node-id=812%3A2119)

<img width="655" alt="Screenshot 2023-06-02 at 6 47 34 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/e70257be-89b6-459e-b268-2452f6234446">

Acceptance criteria:
- confirm recipient page with discord and google icons that you can toggle through (don't worry about the other providers for now)
- after toggling between discord and gmail and entering a recipient and pressing confirm recipient you're brought back to the main /send page and the recipient info is now populated correctly with the recipient and provider you just selected

**Comment by alekseevaiana** [comment]
# Plan
- find a way how to render another component on a page when click on the input, I think about adding a new route but not sure that this is the right way
- check TransferForm and ReviewTransfer components to understand if I can borrow some logic for this issue
- add this new component on a page and toggle buttons, input state depends on buttons
- change placeholder depending on button clicked
- when click 'confirm recipient button' go back to send page form

**Comment by alekseevaiana** [comment]
## Note
Decided to use `react-step-wizard`
