### ISSUE TITLE
Kaching Redesign [6]: Amount to send toggle and confirmation page

### ISSUE THREAD

**Issue by jahabeebs** [UseKeyp/kaching-app#9]
Create the page/component where you can enter an amount to send. Just like the confirm recipient page this is a little tricky because the this will also send data back to the send page.

<img width="373" alt="Screenshot 2023-05-19 at 3 15 56 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/8a0d6f83-0944-4673-b2f8-e630064df02a">

- After pressing confirm amount it will bring us back to the main part of /send with amount info populated

<img width="324" alt="Screenshot 2023-05-19 at 3 16 41 PM" src="https://github.com/UseKeyp/kaching-app/assets/47253537/f5adc443-2960-4d6a-b535-f5a396fd3a29">

Acceptance criteria:
- confirm amount page with number pad you can use to enter digits and validation to make sure a user can't try to send more than their balance
- after entering an amount and pressing confirm amount you're brought back to the main /send page and the amount info is now populated correctly with the amount you've selected

**Comment by alekseevaiana** [comment]
## Plan 
- find a way on how to save data on one page and get this data on another page
- make input with validation (can't try to send more than their balance), 
- make numbers component to fill out input 
- make button to save and send data to /send page

**Comment by pi0neerpat** [comment]
As discussed today, we should not use a modal, and we should not use separate pages for these screens. Potentially a library such as react-step-wizard may be useful here. I recommend sticking to the standard method of using React parent/child components for managing state.
